---

common_extra_packages:
  - python-tox

django_name: machina-vanilla
django_path: "/webapps/{{ django_name }}"
django_requirements_file: "{{ django_project_path }}/requirements.freeze"
django_domain_name: "{{ host_public_domain_name }}"
django_disallow_robots: yes
django_project_repo_url: https://github.com/ellmetha/machina-vanilla.git
django_ssl_only: yes
django_env_variables:
  DJANGO_INSTALL_PATH: "{{ django_path }}"
django_jsonsettings_properties:
  SECRET_KEY: "{{ secret__django_secret_key }}"
  ADMIN_URL: "{{ secret__django_admin_url }}"
  DB_ENGINE: "django.db.backends.postgresql_psycopg2"
  DB_NAME: "{{ django_db_name }}"
  DB_USER: "{{ django_db_user }}"
  DB_PASSWORD: "{{ django_db_password }}"
  DB_HOST: "localhost"
  DB_PORT: ""
  DB_OPTIONS: {}
  ALLOWED_HOSTS: "['{{ django_domain_name }}', ] + {{ django_extra_domain_names|default([]) }}"
  EMAIL_DEV: "{{ secret__django_email_dev }}"
  EMAIL_TEAM: "{{ secret__django_email_team }}"
  DEFAULT_FROM_EMAIL: "{{ secret__django_default_from_email }}"
  SERVER_EMAIL: "{{ secret__django_server_email }}"
  EMAIL_HOST: "{{ secret__django_email_host }}"
  EMAIL_HOST_USER: "{{ secret__django_email_host_user }}"
  EMAIL_HOST_PASSWORD: "{{ secret__django_email_host_password }}"
  RECAPTCHA_PUBLIC_KEY: "{{ secret__django_recaptcha_public_key }}"
  RECAPTCHA_PRIVATE_KEY: "{{ secret__django_recaptcha_private_key }}"
